// tictactoe-vue/src/components/CrossToken.vue
<template>
  <div class="cross">
    <svg
      jsname="uECznc"
      aria-label="X"
      role="img"
      viewBox="0 0 128 128"
      style="visibility: visible"
    >
      <path
        class="hFJ9Ve"
        d="M16,16L112,112"
        style="
          stroke: rgb(84, 84, 84);
          stroke-dasharray: 135.764;
          stroke-dashoffset: 0;
        "
      ></path>
      <path
        class="hFJ9Ve"
        d="M112,16L16,112"
        style="
          stroke: rgb(84, 84, 84);
          stroke-dasharray: 135.764;
          stroke-dashoffset: 0;
        "
      ></path>
    </svg>
  </div>
</template>

<script>
export default {};
</script>

<style scoped>
svg {
  height: 150px;
  width: 150px;
}
svg path {
  stroke-width: 16px;
}
</style>

// tictactoe-react/src/components/CrossToken.js
import React, { Component } from "react";

class CrossToken extends Component {
  render() {
    return (
      <div className="cross">
        <svg jsname="uECznc" aria-label="X" role="img" viewBox="0 0 128 128">
          <path className="hFJ9Ve" d="M16,16L112,112"></path>
          <path className="hFJ9Ve" d="M112,16L16,112"></path>
        </svg>
      </div>
    );
  }
}

export default CrossToken;
