// tictactoe-vue/src/components/NoughtToken.vue
<template>
  <div class="nought">
    <svg
      jsname="D7yUae"
      aria-label="O"
      role="img"
      viewBox="0 0 128 128"
      style="visibility: visible"
    >
      <path
        class="hFJ9Ve"
        d="M64,16A48,48 0 1,0 64,112A48,48 0 1,0 64,16"
        style="stroke: rgb(242, 235, 211); stroke-dasharray: 301.635; stroke-dashoffset: 0"
      ></path>
    </svg>
  </div>
</template>

<style scoped>
svg {
  height: 75px;
  width: 75px;
}
svg path {
  fill: none;
  stroke-width: 16px;
}
</style>

// tictactoe-react/src/components/NoughtToken.js
import React, { Component } from "react";

class NoughtToken extends Component {
  render() {
    return (
      <div className="nought">
        <svg jsname="D7yUae" aria-label="O" role="img" viewBox="0 0 128 128">
          <path
            className="hFJ9Ve"
            d="M64,16A48,48 0 1,0 64,112A48,48 0 1,0 64,16"
          ></path>
        </svg>
      </div>
    );
  }
}

export default NoughtToken;
